/**
 * CityPay Payment API
 *  This CityPay API is a HTTP RESTful payment API used for direct server to server transactional processing. It provides a number of payment mechanisms including: Internet, MOTO, Continuous Authority transaction processing, 3-D Secure decision handling using RFA Secure, Authorisation, Refunding, Pre-Authorisation, Cancellation/Voids and Completion processing. The API is also capable of tokinsed payments using Card Holder Accounts.  ## Compliance and Security Your application will need to adhere to PCI-DSS standards to operate safely and to meet requirements set out by  Visa and MasterCard and the PCI Security Standards Council. These include  * Data must be collected using TLS version 1.2 using [strong cryptography](#enabled-tls-ciphers). We will not accept calls to our API at   lower grade encryption levels. We regularly scan our TLS endpoints for vulnerabilities and perform TLS assessments   as part of our compliance program. * The application must not store sensitive card holder data (CHD) such as the card security code (CSC) or   primary access number (PAN) * The application must not display the full card number on receipts, it is recommended to mask the PAN   and show the last 4 digits. The API will return this for you for ease of receipt creation * If you are developing a website, you will be required to perform regular scans on the network where you host the   application to meet your compliance obligations * You will be required to be PCI Compliant and the application must adhere to the security standard. Further information   is available from [https://www.pcisecuritystandards.org/](https://www.pcisecuritystandards.org/) * The API verifies that the request is for a valid account and originates from a trusted source using the remote IP   address. Our application firewalls analyse data that may be an attempt to break a large number of security common   security vulnerabilities. 
 *
 * Contact: support@citypay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventDataModel model module.
 * @module model/EventDataModel
 */
class EventDataModel {
    /**
     * Constructs a new <code>EventDataModel</code>.
     * @alias module:model/EventDataModel
     */
    constructor() { 
        
        EventDataModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EventDataModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventDataModel} obj Optional instance to populate.
     * @return {module:model/EventDataModel} The populated <code>EventDataModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventDataModel();

            if (data.hasOwnProperty('event_end_date')) {
                obj['event_end_date'] = ApiClient.convertToType(data['event_end_date'], 'Date');
            }
            if (data.hasOwnProperty('event_id')) {
                obj['event_id'] = ApiClient.convertToType(data['event_id'], 'String');
            }
            if (data.hasOwnProperty('event_organiser_id')) {
                obj['event_organiser_id'] = ApiClient.convertToType(data['event_organiser_id'], 'String');
            }
            if (data.hasOwnProperty('event_start_date')) {
                obj['event_start_date'] = ApiClient.convertToType(data['event_start_date'], 'Date');
            }
            if (data.hasOwnProperty('payment_type')) {
                obj['payment_type'] = ApiClient.convertToType(data['payment_type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventDataModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventDataModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['event_id'] && !(typeof data['event_id'] === 'string' || data['event_id'] instanceof String)) {
            throw new Error("Expected the field `event_id` to be a primitive type in the JSON string but got " + data['event_id']);
        }
        // ensure the json data is a string
        if (data['event_organiser_id'] && !(typeof data['event_organiser_id'] === 'string' || data['event_organiser_id'] instanceof String)) {
            throw new Error("Expected the field `event_organiser_id` to be a primitive type in the JSON string but got " + data['event_organiser_id']);
        }
        // ensure the json data is a string
        if (data['payment_type'] && !(typeof data['payment_type'] === 'string' || data['payment_type'] instanceof String)) {
            throw new Error("Expected the field `payment_type` to be a primitive type in the JSON string but got " + data['payment_type']);
        }

        return true;
    }


}



/**
 * The date when the event ends in ISO format (yyyy-MM-dd).
 * @member {Date} event_end_date
 */
EventDataModel.prototype['event_end_date'] = undefined;

/**
 * An id of the event.
 * @member {String} event_id
 */
EventDataModel.prototype['event_id'] = undefined;

/**
 * An id of the event organiser.
 * @member {String} event_organiser_id
 */
EventDataModel.prototype['event_organiser_id'] = undefined;

/**
 * The date when the event starts in ISO format (yyyy-MM-dd).
 * @member {Date} event_start_date
 */
EventDataModel.prototype['event_start_date'] = undefined;

/**
 * The type of payment such as `deposit` or `balance`.
 * @member {String} payment_type
 */
EventDataModel.prototype['payment_type'] = undefined;






export default EventDataModel;

