/**
 * CityPay Payment API
 *  This CityPay API is a HTTP RESTful payment API used for direct server to server transactional processing. It provides a number of payment mechanisms including: Internet, MOTO, Continuous Authority transaction processing, 3-D Secure decision handling using RFA Secure, Authorisation, Refunding, Pre-Authorisation, Cancellation/Voids and Completion processing. The API is also capable of tokinsed payments using Card Holder Accounts.  ## Compliance and Security <aside class=\"notice\">   Before we begin a reminder that your application will need to adhere to PCI-DSS standards to operate safely   and to meet requirements set out by Visa and MasterCard and the PCI Security Standards Council including: </aside>  * Data must be collected using TLS version 1.2 using [strong cryptography](#enabled-tls-ciphers). We will not accept calls to our API at   lower grade encryption levels. We regularly scan our TLS endpoints for vulnerabilities and perform TLS assessments   as part of our compliance program. * The application must not store sensitive card holder data (CHD) such as the card security code (CSC) or   primary access number (PAN) * The application must not display the full card number on receipts, it is recommended to mask the PAN   and show the last 4 digits. The API will return this for you for ease of receipt creation * If you are developing a website, you will be required to perform regular scans on the network where you host the   application to meet your compliance obligations * You will be required to be PCI Compliant and the application must adhere to the security standard. Further information   is available from [https://www.pcisecuritystandards.org/](https://www.pcisecuritystandards.org/) * The API verifies that the request is for a valid account and originates from a trusted source using the remote IP   address. Our application firewalls analyse data that may be an attempt to break a large number of security common   security vulnerabilities.
 *
 * Contact: support@citypay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', process.cwd() + '/src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require(process.cwd() + '/src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.citypay_api_client);
    }
}(this, function (expect, citypay_api_client) {
    'use strict';

    let json = {
        "CardHolderAccount": {
            "account_id": "abc123",
            "cards": [{
                "bin_commercial": false,
                "bin_corporate": false,
                "bin_country_issued": "GBR",
                "bin_currency": "GBP",
                "bin_description": "Visa Classic",
                "bin_eu": false,
                "card_id": "2U1XV3PJSeUXFNzXidACn2TyCzAK",
                "card_status": "ACTIVE",
                "default": true,
                "expmonth": 7,
                "expyear": 2022,
                "label": "TestVisa/0002",
                "label2": "TestVisa/0002,Exp:7/2022",
                "scheme": "TestVisa",
                "token": "ctPCzxq4WxEwWbkG7whRPLRCG27vYFNzsEDNihYmDwqsBc5QEXnFRvq2j5oRyb56ErRVEQaBN7PFMEDtjQQXDQpfxKkp3AxbyeGo61RhKBjFTFegaP4LBZUxFZimsXW8Deae9VyhWSgS2o8AXzTJU9UP3bo8kRcpataxuH3fJj3JHDnyeZt"
            }],
            "contact": {
                "address1": "7 Esplanade",
                "address2": "",
                "address3": "",
                "area": "St Helier",
                "company": "CityPay Ltd",
                "country": "JE",
                "email": "support@citypay.com",
                "firstname": "Joe",
                "lastname": "Wicks",
                "mobile_no": "077112123456",
                "postcode": "JE2 3QA",
                "telephone_no": "+4415341234567",
                "title": "Mr"
            },
            "date_created": "2020-08-01T09:15:24Z",
            "default_card_id": "2U1XV3PJSeUXFNzXidACn2TyCzAK",
            "default_card_index": 0,
            "status": "ACTIVE",
            "unique_id": "Ew3BKeWNdL3qKQU7XK7Sbt2eAL5WFW4AfoASDSA"
        }
    }

    var instance;

    beforeEach(function () {
        instance = new citypay_api_client.ApiClient.instance.deserialize({status: 200, body: json}, citypay_api_client.CardHolderAccount);
    });

    describe('CardHolderAccount', function () {
        it('should create an instance of CardHolderAccount', function () {
            expect(instance).to.be.a(citypay_api_client.CardHolderAccount);
        });

        it('should have the property account_id (base name: "account_id")', function () {
            expect(instance.account_id).to.be("abc123");
        });

        it('should have the property contact (base name: "contact")', function () {
            let contact = instance.contact;
            expect(contact.address1).to.be("7 Esplanade");
            expect(contact.address2).to.be("");
            expect(contact.address3).to.be("");
            expect(contact.area).to.be("St Helier");
            expect(contact.company).to.be("CityPay Ltd");
            expect(contact.country).to.be("JE");
            expect(contact.email).to.be("support@citypay.com");
            expect(contact.firstname).to.be("Joe");
            expect(contact.lastname).to.be("Wicks");
            expect(contact.mobile_no).to.be("077112123456");
            expect(contact.postcode).to.be("JE2 3QA");
            expect(contact.telephone_no).to.be("+4415341234567");
            expect(contact.title).to.be("Mr");
        });

        it('should have the property cards (base name: "cards")', function () {
            expect(instance.cards.length).to.be(1);
            let card = instance.cards[0];
            expect(card.bin_commercial).to.be(false);
            expect(card.bin_corporate).to.be(false);
            expect(card.bin_country_issued).to.be("GBR");
            expect(card.bin_currency).to.be("GBP");
            expect(card.bin_description).to.be("Visa Classic");
            expect(card.bin_eu).to.be(false);
            expect(card.card_id).to.be("2U1XV3PJSeUXFNzXidACn2TyCzAK");
            expect(card.card_status).to.be("ACTIVE");
            expect(card.default).to.be(true);
            expect(card.expmonth).to.be(7);
            expect(card.expyear).to.be(2022);
            expect(card.label).to.be("TestVisa/0002");
            expect(card.label2).to.be("TestVisa/0002,Exp:7/2022");
            expect(card.scheme).to.be("TestVisa");
            expect(card.token).to.be("ctPCzxq4WxEwWbkG7whRPLRCG27vYFNzsEDNihYmDwqsBc5QEXnFRvq2j5oRyb56ErRVEQaBN7PFMEDtjQQXDQpfxKkp3AxbyeGo61RhKBjFTFegaP4LBZUxFZimsXW8Deae9VyhWSgS2o8AXzTJU9UP3bo8kRcpataxuH3fJj3JHDnyeZt");
        });

        it('should have the property date_created (base name: "date_created")', function () {
            expect(instance.date_created.toISOString()).to.be(new Date("2020-08-01T09:15:24Z").toISOString());
        });

        it('should have the property default_card_id (base name: "default_card_id")', function () {
            expect(instance.default_card_id).to.be("2U1XV3PJSeUXFNzXidACn2TyCzAK");
        });

        it('should have the property default_card_index (base name: "default_card_index")', function () {
            expect(instance.default_card_index).to.be(0);
        });

        it('should have the property status (base name: "status")', function () {
            expect(instance.status).to.be("ACTIVE");
        });

        it('should have the property unique_id (base name: "unique_id")', function () {
            expect(instance.unique_id).to.be("Ew3BKeWNdL3qKQU7XK7Sbt2eAL5WFW4AfoASDSA");
        });

    });

}));
