/**
 * CityPay Payment API
 *  This CityPay API is a HTTP RESTful payment API used for direct server to server transactional processing. It provides a number of payment mechanisms including: Internet, MOTO, Continuous Authority transaction processing, 3-D Secure decision handling using RFA Secure, Authorisation, Refunding, Pre-Authorisation, Cancellation/Voids and Completion processing. The API is also capable of tokinsed payments using Card Holder Accounts.  ## Compliance and Security Your application will need to adhere to PCI-DSS standards to operate safely and to meet requirements set out by  Visa and MasterCard and the PCI Security Standards Council. These include  * Data must be collected using TLS version 1.2 using [strong cryptography](#enabled-tls-ciphers). We will not accept calls to our API at   lower grade encryption levels. We regularly scan our TLS endpoints for vulnerabilities and perform TLS assessments   as part of our compliance program. * The application must not store sensitive card holder data (CHD) such as the card security code (CSC) or   primary access number (PAN) * The application must not display the full card number on receipts, it is recommended to mask the PAN   and show the last 4 digits. The API will return this for you for ease of receipt creation * If you are developing a website, you will be required to perform regular scans on the network where you host the   application to meet your compliance obligations * You will be required to be PCI Compliant and the application must adhere to the security standard. Further information   is available from [https://www.pcisecuritystandards.org/](https://www.pcisecuritystandards.org/) * The API verifies that the request is for a valid account and originates from a trusted source using the remote IP   address. Our application firewalls analyse data that may be an attempt to break a large number of security common   security vulnerabilities. 
 *
 * Contact: support@citypay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.citypay_api_client);
  }
}(this, function(expect, citypay_api_client) {
  'use strict';

  var instance;

  beforeEach(function() {
    // instance = new Citypay Api Client.PaylinkCardHolder();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaylinkCardHolder', function() {
    it('should create an instance of PaylinkCardHolder', function() {
      // uncomment below and update the code to test PaylinkCardHolder
      //var // instance = new Citypay Api Client.PaylinkCardHolder();
      //expect(instance).to.be.a(Citypay Api Client.PaylinkCardHolder);
    });

    it('should have the property accept_headers (base name: "accept_headers")', function() {
      // uncomment below and update the code to test the property accept_headers
      //var // instance = new Citypay Api Client.PaylinkCardHolder();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var // instance = new Citypay Api Client.PaylinkCardHolder();
      //expect(instance).to.be();
    });

    it('should have the property company (base name: "company")', function() {
      // uncomment below and update the code to test the property company
      //var // instance = new Citypay Api Client.PaylinkCardHolder();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var // instance = new Citypay Api Client.PaylinkCardHolder();
      //expect(instance).to.be();
    });

    it('should have the property firstname (base name: "firstname")', function() {
      // uncomment below and update the code to test the property firstname
      //var // instance = new Citypay Api Client.PaylinkCardHolder();
      //expect(instance).to.be();
    });

    it('should have the property lastname (base name: "lastname")', function() {
      // uncomment below and update the code to test the property lastname
      //var // instance = new Citypay Api Client.PaylinkCardHolder();
      //expect(instance).to.be();
    });

    it('should have the property mobile_no (base name: "mobile_no")', function() {
      // uncomment below and update the code to test the property mobile_no
      //var // instance = new Citypay Api Client.PaylinkCardHolder();
      //expect(instance).to.be();
    });

    it('should have the property remote_addr (base name: "remote_addr")', function() {
      // uncomment below and update the code to test the property remote_addr
      //var // instance = new Citypay Api Client.PaylinkCardHolder();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var // instance = new Citypay Api Client.PaylinkCardHolder();
      //expect(instance).to.be();
    });

    it('should have the property user_agent (base name: "user_agent")', function() {
      // uncomment below and update the code to test the property user_agent
      //var // instance = new Citypay Api Client.PaylinkCardHolder();
      //expect(instance).to.be();
    });

  });

}));
