# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16', '18', '19', '20', '21' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm install
      - run: npm test
        env:
          CP_CLIENT_ID: ${{secrets.CP_CLIENT_ID}}
          CP_MERCHANT_ID: ${{secrets.CP_MERCHANT_ID}}
          CP_LICENCE_KEY: ${{secrets.CP_LICENCE_KEY}}
